Pull request
aau-giraf/api_client pull request #109
Opened 2022-10-11 12:19 UTC by makelblack159

# pull request

*fixed so pull request works *

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

*tested it by seeing if it pull to the server with settings*

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2022-10-13 08:20 UTC, ltranu20 requested changes
I har (måske ved en fejl) fuldstændig reverted https://github.com/aau-giraf/api_client/pull/104 (showPopup), er dette meningen?

2022-10-13 08:20 UTC, ltranu20 commented on lib/http/http_client.dart
> +    print(body.toString());
Delete

2022-10-13 08:20 UTC, ltranu20 commented on lib/http/http_client.dart
> +    print(body.toString());
Delete

2022-10-13 08:27 UTC, makelblack159 commented
> I har (måske ved en fejl) fuldstændig reverted #104 (showPopup), er dette meningen?

ja da personen der har lavet det ikke har opdateret hele serveren og dermed ikke virker og skulle ikke være i coden hvis det ikke også sendes til databasen så issue #104 skulle ikke havde været aproved da den ikke er tested så den virker

2022-10-13 08:31 UTC, manfredhod commented
> Member

Er det muligt i kan tage fat i SW4 så og finde ud af det?

2022-10-13 08:43 UTC, makelblack159 commented
> > Member
> 
> Er det muligt i kan tage fat i dem som har lavet det? (SW3)

for hvad ?, 
deres ting virker ikke overhovet og er ikke tested ? for at det skulle virke skal der gøres en del arbejde ?

2022-10-13 08:50 UTC, manfredhod commented
> > > Member
> > 
> > 
> > Er det muligt i kan tage fat i dem som har lavet det? (SW3)
> 
> for hvad ?, deres ting virker ikke overhovet og er ikke tested ? for at det skulle virke skal der gøres en del arbejde ?

Vi ved ikke hvad det konkrete problem er så i må nød til at snakke med dem inden vi kan godkende noget.

2022-10-13 09:31 UTC, makelblack159 commented
> > > > Member
> > > 
> > > 
> > > Er det muligt i kan tage fat i dem som har lavet det? (SW3)
> > 
> > 
> > for hvad ?, deres ting virker ikke overhovet og er ikke tested ? for at det skulle virke skal der gøres en del arbejde ?
> 
> Vi ved ikke hvad det konkrete problem er så i må nød til at snakke med dem inden vi kan godkende noget.

vi snakkede om det og de skal gøre deres om så det er okay jeg fjernede det de havde lavet så ikke noget problem her

2022-10-13 11:17 UTC, Malgreen commented on test/database/OfflineDatabase_test.dart
> -    expect(await dbHandler.getUserSettings(jamesbondTestUser.id), isNot(null));
Jeg forstår ikke denne ændring

2022-10-13 11:38 UTC, ltranu20 submitted a review, later dismissed

2022-10-13 11:41 UTC, makelblack159 commented on test/database/OfflineDatabase_test.dart
> -    expect(await dbHandler.getUserSettings(jamesbondTestUser.id), isNot(null));
det fordi der ikke er en settings tap til jamesbondtestuser og da jeg ikke har lavet testen ville jeg sige den skal være null da du ikke kan hente data fra noget der ikke er der ?

2022-10-14 07:42 UTC, mikejensen0 approved these changes, later dismissed
lgtm++ 🥹

2022-12-02 11:46 UTC, closed without merging